// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6f527afd-85d6-421e-a72e-fe3589575848";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLockCloudChange();

float temperature1;
int humidity1;
int lockChart;
bool lockCloud;
bool lockState;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperature1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lockChart, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lockCloud, READWRITE, ON_CHANGE, onLockCloudChange);
  ArduinoCloud.addProperty(lockState, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
